### ISSUE TITLE
Best Farmers Screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#102]
Create a Best Farme screen
- Background color code: EEEEEE
- Cards list should be horizontally scrollable
- Add 5-6 dummy cards

Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[vegetable_app](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app/lib/screens)/

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template 
<img src="https://user-images.githubusercontent.com/90468365/183262438-5d4b8595-8175-44ac-941a-c97de8d9c278.png" width="300">

**Comment by Shreyas-Waghchaure** [comment]
I want to work on this issue

**Comment by SiddhantPawar03** [comment]
> I want to work on this issue

Assigned!

**Comment by Shreyas-Waghchaure** [comment]
can you tell me how to add the floating arrows for card scroll
