### ISSUE TITLE
Timeline of Vegetable

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#103]
Create a Timeline screen
- Background color code: EEEEEE

Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[vegetable_app](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app/lib/screens)/

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template 
<img src="https://user-images.githubusercontent.com/90468365/183262502-8cf5cf59-4335-481d-a478-63dcd955923a.png" width="300">

**Comment by Shreyas-Waghchaure** [comment]
i want to scroll wrok on this issue

**Comment by SiddhantPawar03** [comment]
> i want to scroll wrok on this issue

Assigned!
