### ISSUE TITLE
Data Entry Screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#104]
Create a Cluster screen
- Background color code: EEEEEE

Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[vegetable_app](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app/lib/screens)/

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template 
<img src="https://user-images.githubusercontent.com/90468365/183262575-f8dccbc6-34c8-4668-b2c5-de912d81fd87.png" width="300">

**Comment by Shreyas-Waghchaure** [comment]
i want to work on this issue

**Comment by Shreyas-Waghchaure** [comment]
i want to work on this issue

**Comment by SiddhantPawar03** [comment]
> i want to work on this issue

Assigned!
