### ISSUE TITLE
Dealer Screens

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#105]
Create Dealer screens
- Background color code: EEEEEE

Folder Structure: 
Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[vegetable_app](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app/lib/screens)/

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template (must follow)
Screen 1 | Screen 2 
|:----------------:|:----------------:|
<img src="https://user-images.githubusercontent.com/90468365/183262727-a8162c06-edda-4cd1-ac2d-9281a04ab4b5.png" width="300">|<img src="https://user-images.githubusercontent.com/90468365/183262744-5c3f4475-cacf-4186-ad3e-e0b400228799.png" width="300">

**Comment by Maruti54** [comment]
I would like to work on this.

**Comment by SiddhantPawar03** [comment]
> I would like to work on this.

Assigned!
