### ISSUE TITLE
Dealer Screen 2

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#106]
Create a Dealer screen
- Background color code: EEEEEE

Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[vegetable_app](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app/lib/screens)/

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template 
<img src="https://user-images.githubusercontent.com/90468365/183262806-b7bb9a31-4c3e-4add-864c-d8a0955b294b.png" width="300">

**Comment by Maruti54** [comment]
I would like to work on this.

**Comment by SiddhantPawar03** [comment]
Hey @Maruti54 !
It's been more than the expected timeline, can you update on the issue?

**Comment by Maruti54** [comment]
Yeah working on it.
