### ISSUE TITLE
Registration Page - II

### ISSUE THREAD

**Issue by SiddhantPawar03** [The-Robotics-Forum/flutter-ui-templates#121]
Create registration page - II with the following features:

Folder Structure: [flutter-ui-templates](https://github.com/The-Robotics-Forum/flutter-ui-templates)/[projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[canteen_app](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/canteen_app)/lib/

Figma Template Link: https://www.figma.com/file/4lgs6uG2ZI0e7g2I0uCPuE/Student-Mess-Management-System-(Copy)?node-id=56%3A240 (iPhone 13 / 13 Pro - 10)
https://www.figma.com/file/4lgs6uG2ZI0e7g2I0uCPuE/Student-Mess-Management-System-(Copy)?node-id=56%3A305 (iPhone 13 / 13 Pro - 11)

**Comment by Shreyas-Waghchaure** [comment]
I want to work on this issue

**Comment by SiddhantPawar03** [comment]
> I want to work on this issue

Assigned!

**Comment by Shreyas-Waghchaure** [comment]
what functionality is needed to add in this issue for profile pic selection

**Comment by Pavan49719** [comment]
@Shreyas-Waghchaure 
use this packages https://pub.dev/packages/image_picker
