### ISSUE TITLE
Set Location

### ISSUE THREAD

**Issue by SiddhantPawar03** [The-Robotics-Forum/flutter-ui-templates#122]
Create a set location page with the following features:

Folder Structure: [flutter-ui-templates](https://github.com/The-Robotics-Forum/flutter-ui-templates)/[projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[canteen_app](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/canteen_app)/lib/

Figma Template Link: https://www.figma.com/file/4lgs6uG2ZI0e7g2I0uCPuE/Student-Mess-Management-System-(Copy)?node-id=56%3A705 (iPhone 13 / 13 Pro - 12)

**Comment by Shreyas-Waghchaure** [comment]
I want to work on this issue. 
Can you tell me where do i put the retrived location form user

**Comment by SiddhantPawar03** [comment]
> I want to work on this issue. Can you tell me where do i put the retrived location form user

Assigned!

**Comment by SiddhantPawar03** [comment]
> I want to work on this issue. Can you tell me where do i put the retrived location form user

Just store location for while
