### ISSUE TITLE
Login Page - II

### ISSUE THREAD

**Issue by SiddhantPawar03** [The-Robotics-Forum/flutter-ui-templates#124]
Create  login screen  - II with the following features:

Folder Structure: [flutter-ui-templates](https://github.com/The-Robotics-Forum/flutter-ui-templates)/[projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[canteen_app](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/canteen_app)/lib/

Figma Template Link: https://www.figma.com/file/4lgs6uG2ZI0e7g2I0uCPuE/Student-Mess-Management-System-(Copy)?node-id=4%3A2 (iPhone 13 / 13 Pro - 1)

**Comment by Shreyas-Waghchaure** [comment]
I want to work on this issue

**Comment by SiddhantPawar03** [comment]
> I want to work on this issue

Assigned!
