### ISSUE TITLE
Order Page

### ISSUE THREAD

**Issue by SiddhantPawar03** [The-Robotics-Forum/flutter-ui-templates#125]
Create order page with the following features:

Folder Structure: [flutter-ui-templates](https://github.com/The-Robotics-Forum/flutter-ui-templates)/[projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[canteen_app](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/canteen_app)/lib/

Figma Template Link: https://www.figma.com/file/4lgs6uG2ZI0e7g2I0uCPuE/Student-Mess-Management-System-(Copy)?node-id=57%3A1518 (iPhone 13 / 13 Pro - 14)
https://www.figma.com/file/4lgs6uG2ZI0e7g2I0uCPuE/Student-Mess-Management-System-(Copy)?node-id=57%3A2139 (iPhone 13 / 13 Pro - 15)

**Comment by Shreyas-Waghchaure** [comment]
I want to work on this issue

**Comment by SiddhantPawar03** [comment]
> I want to work on this issue

Assigned!
