### ISSUE TITLE
Design the readme and fix typo

### ISSUE THREAD

**Issue by Rakesh9100** [The-Robotics-Forum/flutter-ui-templates#13]

**Comment by Pavan49719** [comment]
Please summarize what changes you are going to make.

**Comment by Rakesh9100** [comment]
> Please summarize what changes you are going to make. @Rakesh9100

I am opening a PR showing up the changes.

**Comment by Pavan49719** [comment]
> > Please summarize what changes you are going to make. @Rakesh9100
> 
> I am opening a PR showing up the changes.
Okay go on.
