### ISSUE TITLE
Add navigator to login screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#17]
Add a navigator to the login screen
On clicking the login button it should be navigated to a dashboard
Also add button in dashboard's screen which directs to cart screen.
And create separate function for each button in login screen.
Folder Structure: packages/login_screen/login.dart

**Comment by Maruti54** [comment]
I would like to work on this.

**Comment by Pavan49719** [comment]
Yeah go on. Assigned!
