### ISSUE TITLE
Bottom Navigation Bar

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#21]
Create a Bottom navigation bar on the dashboard screen.
- Should have at least 4 items(Bottom tabs)
- Create a separate Screen for each tab (Just add label name to those screens for now)
- Do use icons

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Folder Structure: packages/bottom_navigation_bar/
(Create this folder)

**Comment by Maruti54** [comment]
I would like to work on this.

**Comment by SiddhantPawar03** [comment]
> I would like to work on this.

Assigned!
