### ISSUE TITLE
Onboarding Screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#23]
Create an onboarding screen
- 3 sub-screens should be there before the login screen
- Add them after the Splash screen
- Add an attractive animation/transitions between each screen

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Folder Structure: packages/onboarding/
(Create this folder)

**Comment by Maruti54** [comment]
I would like to work on this.
Please tell me about 3 sub screens in more detail.

**Comment by Pavan49719** [comment]
@Maruti54 Just google it. You will get all the detailed UI information there.

> I would like to work on this. Please tell me about 3 sub screens in more detail.

Just google it, You will get all the detailed information there.

**Comment by Maruti54** [comment]
Yeah got it 👍
