### ISSUE TITLE
Animation in splash screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#24]
Add an animation to the TRF logo on the splash screen
(Do any of the below)
- Transition to the logo (left to center, top to center, etc)
- Zoom in/out logo
- Rotating logo

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Folder Structure: packages/splash_screen/

**Comment by Shreyas-Waghchaure** [comment]
Hey can I work on this issue

**Comment by SiddhantPawar03** [comment]
> Hey can I work on this issue

Assigned!
