### ISSUE TITLE
Day/night theme mode

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#29]
Implement a Day/Night mode 
- Create a toggle button in the drawer
- Use shared pref for storing the data of theme mode

**Comment by SiddhantPawar03** [comment]
> I want to work on this issue can you assign me

Assigned!

**Comment by Shreyas-Waghchaure** [comment]
hey i was not able to do the changes you can give this problem to someone else, i will take another issue

**Comment by Maruti54** [comment]
I would like to work on this.

**Comment by SiddhantPawar03** [comment]
> I would like to work on this.

Assigned!
