### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#3]
Create an attractive splash screen with the following features:
- Organization logo and name
- Screen duration:  3 sec

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when your push changes.

Folder Structure: packages/splash_screen/

**Comment by Aspireve** [comment]
Hey @Pavan49719  Could I do this?

**Comment by SiddhantPawar03** [comment]
> Hi @SiddhantPawar03 I am sorry but I don't think I might be able to do this as I am not able to run flutter through android studio now. I'm really sorry for any inconvenience I caused due to it

No problem!
If any help required you may reach out us in discord as well.

**Comment by Shreyas-Waghchaure** [comment]
Hey @SiddhantPawar03 Can I work on this issue?

**Comment by SiddhantPawar03** [comment]
> Hey @SiddhantPawar03 Can I work on this issue?

Assigned!
