### ISSUE TITLE
Web View in profile card

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#33]
Add a web view for buttons like Twitter, Facebook in the profile card
- Can use URL launcher package 
- Add hardcoded links in the launcher
- After clicking on the buttons, the web view screen should get opened 

Folder Structure: packages/Profile_Card/

**Comment by Maruti54** [comment]
I would like to work on this.

**Comment by SiddhantPawar03** [comment]
> I would like to work on this.

Assigned!
