### ISSUE TITLE
Drawer

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#4]
Create a side drawer that has 
- Profile card (Profile picture and mail ID)
- Other buttons (like settings, about, help, feedback, etc)
- Do use icons as well

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when your push changes.

Folder Structure: packages/drawer/

**Comment by Shreyas-Waghchaure** [comment]
Hey I am from hsoc and interested in this issue can you assign it and explain me

**Comment by SiddhantPawar03** [comment]
> Hey I am from hsoc and interested in this issue can you assign it and explain me

Yes! You may start working on issue also try to go through all guidelines.
