### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#40]
Create an attractive splash screen with the following features:
- [logo](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/projects/ev_stations/assets/splash_image.jpeg) 
- Screen duration: 3 sec
- Background colour code: 151A24

Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[ev_stations](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens)/splash.dart

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template (Must follow)
<img src="https://user-images.githubusercontent.com/90468365/180286569-13878576-1f54-463c-932d-8e06a2c264c4.png" width="300">

**Comment by Maruti54** [comment]
I would like to work on this.

**Comment by SiddhantPawar03** [comment]
> I would like to work on this.

Assigned!
