### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#41]
Create a login screen that has
- Background colour code: 7D7D7D
- Login button colour code: 20BCDE

Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[ev_stations](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens)/login.dart

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template (must follow)
<img src="https://user-images.githubusercontent.com/90468365/180289590-43c4a2fb-fa07-4c95-a8c9-db92c589f8b0.png" width="300">

**Comment by Shreyas-Waghchaure** [comment]
i want to work on this issue assign me

**Comment by Shreyas-Waghchaure** [comment]
I would like to work on this issue assign me

**Comment by SiddhantPawar03** [comment]
> I would like to work on this issue assign me

Assigned!

**Comment by Shreyas-Waghchaure** [comment]
Hey I am Getting Following Error:
Error on line 285, column 3 of pubspec.lock: Duplicate mapping key.
    ╷
285 │   dart: ">=2.17.0 <3.0.0"
    │   ^^^^
    ╵
pub get failed (65;     ╵)
