### ISSUE TITLE
Drawer

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#43]
Create a drawer that has
- Background colour code: 454545

Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[ev_stations](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens)/[users](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens/users)/users/drawer.dart

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template (must follow)
<img src="https://user-images.githubusercontent.com/90468365/180297892-cb19277c-afd9-404e-8eec-fb76f0a327d9.png" width="300">

**Comment by Shreyas-Waghchaure** [comment]
I would like to work on this Issue please assign me

**Comment by SiddhantPawar03** [comment]
> I would like to work on this Issue please assign me

Assigned!
