### ISSUE TITLE
Charging Station Screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#45]
Create a charging station screen
- Background colour code: 454545
- button colour code: 20BCDE 

Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[ev_stations](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens)/users/charging.dart

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template (must follow)
<img src="https://user-images.githubusercontent.com/90468365/180299842-0678efe6-2524-4573-ab26-aada36b8321a.png" width="300">

**Comment by Shreyas-Waghchaure** [comment]
I want to work on this issue assign me

**Comment by Shreyas-Waghchaure** [comment]
Can you tell me what the bricks below Time label called or i just have to hardcode it

**Comment by SiddhantPawar03** [comment]
> I want to work on this issue assign me

Assigned!

**Comment by SiddhantPawar03** [comment]
> Can you tell me what the bricks below Time label called or i just have to hardcode it

You may hardcode it.

**Comment by Shreyas-Waghchaure** [comment]
![image](https://user-images.githubusercontent.com/72643976/180428836-349c8fdf-7423-4a13-b64c-7e61fc4128b9.png)
can you help me with this i am struggling to add this in application

**Comment by Pavan49719** [comment]
> ![image](https://user-images.githubusercontent.com/72643976/180428836-349c8fdf-7423-4a13-b64c-7e61fc4128b9.png) can you help me with this i am struggling to add this in application

It's a dropdown list with just min & hour as options. You can refer [this](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/projects/templates/lib/packages/dropdown/dropdown.dart)
