### ISSUE TITLE
Connection Screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#46]
Create a connection screen that has
- [Image](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/projects/ev_stations/assets/charging.jpeg)
- Background colour code: 454545

Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[ev_stations](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens)/users/connection.dart

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template (must follow)
<img src="https://user-images.githubusercontent.com/90468365/180300957-6bd81308-ed71-4df1-acb9-578d78188726.png" width="300">

**Comment by Maruti54** [comment]
I would like to work on this

**Comment by SiddhantPawar03** [comment]
> I would like to work on this

Assigned!
