### ISSUE TITLE
Confirmation Screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#47]
Create a confirmation screen that has
- [Image](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/projects/ev_stations/assets/car2.jpeg)
- Background colour code: 454545
- Login button colour code: 20BCDE

Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[ev_stations](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens)/users/confirming.dart

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template (must follow)
<img src="https://user-images.githubusercontent.com/90468365/180301460-1fff3e9e-ac52-4c92-a98d-acf285a90b18.png" width="300">

**Comment by Shreyas-Waghchaure** [comment]
I want to work on this issue assign me

**Comment by Pavan49719** [comment]
Assigned !!
