### ISSUE TITLE
Charging Screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#48]
Create a charging screen 
- Circular progress bar should be updated dynamically
- Background colour code: 7D7D7D
- Login button colour code: 20BCDE

Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[ev_stations](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens)/users/charging.dart

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template (must follow)
<img src="https://user-images.githubusercontent.com/90468365/180302367-9a18caa1-7e9c-400b-ad2a-a81018046cf3.png" width="300">

**Comment by Shreyas-Waghchaure** [comment]
I would like to work on this issue assign me

**Comment by SiddhantPawar03** [comment]
> I would like to work on this issue assign me

Assigned!

**Comment by Shreyas-Waghchaure** [comment]
Hey can you tell me in which file i should write code 
cause same file structure is given for charging station screen

**Comment by SiddhantPawar03** [comment]
> Hey can you tell me in which file i should write code cause same file structure is given for charging station screen

You may create a new file i.e charging_screen.dart but the folder structure should be [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[ev_stations](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens)/users/<file_name.dart>

**Comment by Shreyas-Waghchaure** [comment]
> > Hey can you tell me in which file i should write code cause same file structure is given for charging station screen
> 
> You may create a new file i.e charging_screen.dart but the folder structure should be [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[ev_stations](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens)/users/<file_name.dart>

Okay thank you
