### ISSUE TITLE
Success Screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#49]
Create a success screen that has
- Background colour code: 454545
- Login button colour code: 20BCDE

Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[ev_stations](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens)/users/success.dart

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template (must follow)
<img src="https://user-images.githubusercontent.com/90468365/180303158-c9400fcd-6790-4753-a2ec-25021c9cb334.png" width="300">

**Comment by faizanMayo786** [comment]
I will Start Coding for this Ui immediately

**Comment by Pavan49719** [comment]
> I will Start Coding for this Ui immediately

Are you a HSoC Contributor? If yes please send your discord username Or message us in the general channel on the discord

**Comment by faizanMayo786** [comment]
Sir i am not the member but can i be?

**Comment by faizanMayo786** [comment]
I just want to contribute

**Comment by Pavan49719** [comment]
> Sir i am not the member but can i be?

https://soc.hackclubrait.co/
Register here to contribute to this repo

**Comment by faizanMayo786** [comment]
Ok Thanks

**Comment by piyushkumar12111111** [comment]
Sir i can work on this

**Comment by piyushkumar12111111** [comment]
We only have to make this ui??

**Comment by piyushkumar12111111** [comment]
Sir i have no experience with git , I want to ask the code we have to write in  Android studio and upload here as zip??

**Comment by SiddhantPawar03** [comment]
> Sir i have no experience with git , I want to ask the code we have to write in Android studio and upload here as zip??

Follow contributing.md for same!

**Comment by piyushkumar12111111** [comment]
Ok sir

**Comment by piyushkumar12111111** [comment]
Please assign me this UI project.

**Comment by SiddhantPawar03** [comment]
> Please assign me this UI project.

Assigned!

**Comment by SiddhantPawar03** [comment]
> Please assign me this UI project.

@piyushkumar12111111 any updates?

**Comment by piyushkumar12111111** [comment]
Yes sir working on it

**Comment by piyushkumar12111111** [comment]
Sir if i have some doubt how can i ask

**Comment by SiddhantPawar03** [comment]
> Sir if i have some doubt how can i ask

You may ask here itself!

**Comment by SiddhantPawar03** [comment]
@piyushkumar12111111 any updates?
Please do the issue asap our we need to unassign it if anyone requests for same.

**Comment by Shreyas-Waghchaure** [comment]
i want to work on this issue

**Comment by SiddhantPawar03** [comment]
> i want to work on this issue

Assigned!
