### ISSUE TITLE
login screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#5]
Create a login screen that has:
- Text fields for email, password, etc.
- Password hide-visibility button
- forgot password button
- button for: Or login with Google, Facebook, etc

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when your push changes.

Folder Structure: packages/login_screen/

**Comment by Maruti54** [comment]
I would like to work on this issue.

**Comment by SiddhantPawar03** [comment]
> I would like to work on this issue.

Yes, proceed ahead. Check all expected guidelines.
