### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#6]
Create a setting page that has
- Buttons like account, Storage and data, privacy, security, help, invite, etc
- Do use icons along with text widgets
- Make this list scrollable vertically
- Do use a third-party font package & use attractive fonts

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when your push changes.

Folder Structure: packages/settings_screen/

**Comment by Shreyas-Waghchaure** [comment]
i Would like to work on this issue can you explain me details

**Comment by Pavan49719** [comment]
> i Would like to work on this issue can you explain me details

Just do a UI with everything hardcoded. You can refer Setting page of WhatsApp or telegram.

**Comment by Shreyas-Waghchaure** [comment]
Okay got it
