### ISSUE TITLE
Dynamic battery level & Navigators

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#60]
- Make battery level dynamic.
- Add all required functionalities to the dashboard
- Add navigators to connect all the pages

**Comment by Maruti54** [comment]
I would like to work on this.

**Comment by Pavan49719** [comment]
Assigned!!

**Comment by Pavan49719** [comment]
@Maruti54 Add navigators to all the screens that are present now.

**Comment by Maruti54** [comment]
Yeah
