### ISSUE TITLE
Stations Dashboard

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#65]
Create a dashboard screen that has
- Background color code: 454545
- Battery percentage should be dynamic

Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[ev_stations](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens)/[stations](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens/stations)/station_dashboard.dart

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template (must follow)
<img src="https://user-images.githubusercontent.com/90468365/180844385-298adb8a-9759-4f98-bdd2-828ac2dcabc8.png" width="300">

**Comment by Maruti54** [comment]
I would like to work on this.

**Comment by SiddhantPawar03** [comment]
> I would like to work on this.

Assigned!
