### ISSUE TITLE
Statistics Line Chart

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#68]
Create a Statistics Line Chart screen that has
- Background colour code: 454545

Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[ev_stations](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens)/users/statistics.dart

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template (must follow)
<img src="https://user-images.githubusercontent.com/90468365/180848522-3a157f4c-f972-4410-bd86-63db3f9a37f2.png" width="300">

**Comment by Shreyas-Waghchaure** [comment]
I would like to work on this issue

**Comment by SiddhantPawar03** [comment]
> I would like to work on this issue

Assigned!
