### ISSUE TITLE
Cart Screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#7]
Create a cart screen that has
- Listview of cards
- Each card contains an image of the product, a title, and a short description
- Add shadow/elevation to the card
- Add to cart button
- Make a list scrollable

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when your push changes.

Folder Structure: packages/cart_screen/

**Comment by Maruti54** [comment]
I would like to work on this.

**Comment by SiddhantPawar03** [comment]
> I would like to work on this.

Assigned!
