### ISSUE TITLE
Add badges in the readme

### ISSUE THREAD

**Issue by khushimarothi** [The-Robotics-Forum/flutter-ui-templates#75]
![Screenshot_20220727-142533_Samsung Internet](https://user-images.githubusercontent.com/85816852/181412492-41601680-0df1-4ed5-95ff-aff94a660672.jpg)
Will add these kind of badges on the readme file.

**Comment by khushimarothi** [comment]
Please assign it to me.

**Comment by SiddhantPawar03** [comment]
> Please assign it to me.

Assigned!
It would be better if you add contributors, project admins info (By creating table & photos etc.)  further you may style readme.

**Comment by khushimarothi** [comment]
okay will try to implement that

**Comment by khushimarothi** [comment]
Kindly add MIT lincense in the repo

**Comment by khushimarothi** [comment]
@SiddhantPawar03  it would be great if you can provide me the linkedin id of both project admins on the discord server or here itself.

**Comment by SiddhantPawar03** [comment]
> @SiddhantPawar03 it would be great if you can provide me the linkedin id of both project admins on the discord server or here itself.

Siddhant: https://www.linkedin.com/in/siddhant-pawar-398a05201/
Pavan: https://www.linkedin.com/in/pavan-bhadane-033b26205/
