### ISSUE TITLE
Registration Screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#77]
Create a Registration screen 
- Can use [this](https://pub.dev/packages/geolocator) package
- Location should be in coordinates format 

Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[ev_stations](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens)/[registration](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens/registration)/registration.dart

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template (must follow)
<img src="https://user-images.githubusercontent.com/90468365/181608219-6d5aeeb7-60b0-445b-9353-dd6880605f95.png" width="300">

**Comment by Shreyas-Waghchaure** [comment]
I want to work on this issue

**Comment by SiddhantPawar03** [comment]
> I want to work on this issue

Assigned!

**Comment by Shreyas-Waghchaure** [comment]
hey@SiddhantPawar03 @Pavan49719 how the location should be in longitude and latititude format or text address format and aslo where to display the address

**Comment by SiddhantPawar03** [comment]
> hey @SiddhantPawar03 @Pavan49719 how the location should be in longitude and latititude format or text address as i added Text address format and also where to display the address

Update the location in text format. You may display location in given textarea itself

**Comment by Shreyas-Waghchaure** [comment]
Can you tell me how can i add Address in textarea any method for that

**Comment by Shreyas-Waghchaure** [comment]
> Can you tell me how can i add Address in textarea any method for that i added this but not able to add in textfield ![Screenshot_1659100817](https://user-images.githubusercontent.com/72643976/181769312-228d322e-08f9-4e65-ae4d-b622d3c4b002.png)

Hey @Pavan49719 @SiddhantPawar03 can you guide me in this
