### ISSUE TITLE
Verification Screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#78]
Create a charging station screen
- Background colour code: 454545

Folder Structure: 
1. [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[ev_stations](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens)/[registration](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens/registration)/verification.dart
2. [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[ev_stations](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens)/[registration](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens/registration)/password.dart

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template (must follow)
Screen 1 | Screen 2 
|:----------------:|:----------------:|
<img src="https://user-images.githubusercontent.com/90468365/181611620-8c4182fb-1a42-41ab-bc8b-713e0822d96b.png" width="300">|<img src="https://user-images.githubusercontent.com/90468365/181613464-934820f8-a24d-402b-9db0-fd31120878c1.png" width="300">

**Comment by Maruti54** [comment]
I would like to work on this.

**Comment by SiddhantPawar03** [comment]
> I would like to work on this.

Assigned!
