### ISSUE TITLE
Register User & Station Screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#79]
Create Register User & Station screen
- Background colour code: 454545

Folder Structure: 
1. [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[ev_stations](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens)/[registration](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens/registration)/register_user.dart
2. [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[ev_stations](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens)/[registration](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens/registration)/register_station.dart

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template (must follow)
Screen 1 | Screen 2 
|:----------------:|:----------------:|
<img src="https://user-images.githubusercontent.com/90468365/181615324-18f9348d-9a47-444b-9792-e12e76b45e95.png" width="300">|<img src="https://user-images.githubusercontent.com/90468365/181615365-2362ec43-c3a1-406e-bdfd-66c15063a8a8.png" width="300">

**Comment by SiddhantPawar03** [comment]
> I would like to work on this.

Assigned!
