### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#83]
Create a Login screen
- Background colour code: EEEEEE
- button colour code: 20BCDE 

Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[vegetable_app](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app/lib/screens)/login.dart

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template (must follow)
<img src="https://user-images.githubusercontent.com/90468365/181811751-eca23df6-0c57-42f6-9828-eb9d04bde92b.png" width="300">

**Comment by SiddhantPawar03** [comment]
> I would like to work on this.

Assigned!

**Comment by Shreyas-Waghchaure** [comment]
Can I work on this issue if he is not working

**Comment by SiddhantPawar03** [comment]
@Maruti54 any update?

**Comment by SiddhantPawar03** [comment]
> Can I work on this issue if he is not working

By the time you may solve another pending issues!
