### ISSUE TITLE
Password and Verification screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#85]
Create Password and Verification screen
- Background colour code: 454545
- Button colour code: 20BCDE 

Folder Structure: 
1. [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[ev_stations](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens)/[registration](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens/registration)/verification.dart
2. [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[ev_stations](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens)/[registration](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/ev_stations/lib/screens/registration)/password.dart

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template (must follow)
Screen 1 | Screen 2 
|:----------------:|:----------------:|
<img src="https://user-images.githubusercontent.com/90468365/181814207-4540c1ce-e91c-4c7b-bc6d-f344cb6fd013.png" width="300">|<img src="https://user-images.githubusercontent.com/90468365/181814259-eec05428-d404-42b7-b9e8-b7d9afa9f025.png" width="300">

**Comment by Maruti54** [comment]
I would like to work on this
