### ISSUE TITLE
Vegetable Information Screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#87]
Create a Vegetable information screen
- Background colour code: EEEEEE
- button colour code: 20BCDE 

Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[vegetable_app](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app/lib/screens)/vege_info.dart

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template (must follow)
<img src="https://user-images.githubusercontent.com/90468365/181816318-9b33187d-bf36-4118-a7bd-0b0b3cdb3088.png" width="300">

**Comment by Shreyas-Waghchaure** [comment]
I want to work on this issue

**Comment by Shreyas-Waghchaure** [comment]
can you tell me what i have to add below Quantity, freshness, Ripeness respectively..?

**Comment by SiddhantPawar03** [comment]
> can you tell me what i have to add below Quantity, freshness, Ripeness respectively..?

For quantity add integer value, freshness & ripeness add percentage value.
This vallue should be taken from user not should be hardcoded

**Comment by SiddhantPawar03** [comment]
> I want to work on this issue

Assigned!
