### ISSUE TITLE
Notification Screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#88]
Create a notification screen
- List should be scrollable
- Background colour code: EEEEEE
- Tile colour code: 20BCDE 

Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[vegetable_app](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app/lib/screens)/notification.dart

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template (must follow)
<img src="https://user-images.githubusercontent.com/90468365/181816818-06ac4158-fd1b-41e4-bfb3-a556072270d7.png" width="300">

**Comment by Shreyas-Waghchaure** [comment]
I want to work on this issue

**Comment by SiddhantPawar03** [comment]
> I want to work on this issue

Assigned!
