### ISSUE TITLE
Cluster Graph

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#97]
Create a Cluster screen
- Background color code: EEEEEE
- Hardcode numbers for a cluster
No need to do exactly like a UI given.
Just create a map screen with a cluster(density) .

Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[vegetable_app](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app/lib/screens)/

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template 
<img src="https://user-images.githubusercontent.com/90468365/183261517-9e179460-b46a-4c3c-8cf1-0785a74f761a.png" width="300">

**Comment by Shreyas-Waghchaure** [comment]
I want to work on this issue

**Comment by SiddhantPawar03** [comment]
> I want to work on this issue

Assigned!

**Comment by Shreyas-Waghchaure** [comment]
can you provide me api key for integration of google maps
