### ISSUE TITLE
History Screen

### ISSUE THREAD

**Issue by Pavan49719** [The-Robotics-Forum/flutter-ui-templates#99]
Create a History screen
- Background color code: EEEEEE
- Hardcode numbers for a cluster
- Create a history list for both Farmer & Dealer tab
- List should be Scrollable

Folder Structure: [projects](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects)/[vegetable_app](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app)/[lib](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app/lib)/[screens](https://github.com/The-Robotics-Forum/flutter-ui-templates/tree/main/projects/vegetable_app/lib/screens)/

Follow the [Guidelines](https://github.com/The-Robotics-Forum/flutter-ui-templates/blob/main/CONTRIBUTING.md) and code of conduct when you push changes.

Figma template 
<img src="https://user-images.githubusercontent.com/90468365/183262157-2613af15-0c0e-4c7c-9193-f57063fbce4c.png" width="300">

**Comment by Shreyas-Waghchaure** [comment]
I want to work on this issue

**Comment by SiddhantPawar03** [comment]
> I want to work on this issue

Assigned!
